import unittest


class AddEmployee(unittest.TestCase):
    def setUp(self):
        # start browser
        pass
    def tearDown(self):
        # quit browser
        pass
    def login_as_admin(self):
        # login as admin
        pass
    def add_employee(self):
        # create new employee/create first and last name, save generated user's ID
        pass

    def create_employee_credentials(self):
        # check 'Create login details' and create user name and user's password
        pass

    def search_employee_by_name(self):
        # as admin search employee by first name/last name/both
        pass

    def search_employee_by_ID(self):
        # search employee by ID (generated by system)
        pass

    def logout(self):
        # logout
        pass

    def login_as_new_employee(self):
        pass

    def test_new_employee_added_and_login(self):
        pass




if __name__ == '__main__':
    unittest.main()
