import unittest
from telnetlib import EC

from faker import Faker
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait

from fixtures.base_fixture import AdminLoginFixture


class AddEmployee(AdminLoginFixture):
    def add_employee(self):
        # create new employee/create first and last name, save generated user's ID
        browser = self.browser
        fake = Faker()
        first_name = fake.first_name()
        last_name = fake.last_name()

        browser.find_element(By.ID, 'btnAdd').click()
        browser.find_element(By.ID, 'firstName').send_keys(first_name)
        browser.find_element(By.ID, 'lastName').send_keys(last_name)
        new_employee_id = browser.find_element(By.ID, 'employeeId').get_attribute('value')
        return first_name, last_name, new_employee_id

    def create_employee_credentials(self, first_name,new_employee_id):
        # check 'Create login details' and create user name and user's password
        browser = self.browser
        fake = Faker()
        user_name = f"{first_name}{new_employee_id}"
        password = fake.password()
        browser.find_element(By.ID, 'chkLogin').click()
        browser.find_element(By.ID, 'user_name').send_keys(user_name)
        browser.find_element(By.ID, 'password').send_keys(password)
        browser.find_element(By.ID, 're_password').send_keys(password)
        browser.find_element(By.ID, 'btnSave').click()


    def search_employee_by_name(self, first_name, last_name):
        # as admin search employee by first name/last name/both
        self.browser.get('http://hrm-online.portnov.com')
        browser = self.browser
        browser.find_element(By.ID, 'menu_admin_viewAdminModule').click()
        browser.find_element(By.ID, 'user_name').send_keys(user_name)
        browser.find_element(By.ID, 'password').send_keys(password)
        browser.find_element(By.ID, 're_password').send_keys(password)
        browser.find_element(By.ID, 'btnSave').click()

    def search_employee_by_ID(self):
        # search employee by ID (generated by system)
        pass

    def logout(self):
        # logout
        pass

    def login_as_new_employee(self, user_name, password):
        browser = self.browser
        browser.find_element(By.ID, 'txtUsername').send_keys(user_name)
        browser.find_element(By.ID, 'txtPassword').send_keys(password)
        browser.find_element(By.ID, 'btnLogin').click()
        self.wait = WebDriverWait(browser, 5)
        self.wait.until(EC.presence_of_element_located(self.welcome_message_element))


def test_new_employee_added_and_login(self):
        pass




if __name__ == '__main__':
    unittest.main()
